name: CI

on:
  push:
  pull_request:
  repository_dispatch:
    types: [run_build]

jobs:
  configurator:
    runs-on: ubuntu-latest
    container: ps2dev/ps2dev:latest
    steps:
      - name: Install dependencies
        run: |
          apk add build-base git zip nodejs

      - uses: actions/checkout@v2

      - name: Compile ps2plus-configurator
        run: |
          make
          git config --global --add safe.directory "*"
          git ls-files -i --exclude-standard -c

      - name: Get short SHA
        id: slug
        run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"

      - name: Upload output file
        uses: actions/upload-artifact@v2
        with:
          name: ps2plus-configurator.elf
          path: dist/PS2PLMAN.ELF

  firmware-PIC18F46K42:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Run the Docker Compose build step
        run: docker compose -f docker/docker-compose.yml run firmware-pic18f46k42

      - name: Get short SHA
        id: slug
        run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"

      - name: Upload firmware
        uses: actions/upload-artifact@v2
        with:
          name: ps2plus-PIC18F46K42-firmware.hex
          path: dist/ps2plus-PIC18F46K42-firmware.hex

      - name: Upload bootloader
        uses: actions/upload-artifact@v2
        with:
          name: ps2plus-PIC18F46K42-bootloader.hex
          path: dist/ps2plus-PIC18F46K42-bootloader.hex